### ISSUE TITLE
Não baixando "PREPENDED 'busca_ano' : ''"

### ISSUE THREAD

**Issue by andr3medeiros** [hernan604/WWW-Tabela-Fipe#3]
Boa tarde Hernan!

Baixei na data de hoje o seu software pois tínhamos um em php que fazia basicamente o mesmo que o seu, mas infelizmente me parece que a estrutura do site mudou e essa ferramenta em php não funciona mais. Ao tentar rodar o seu software ele fica repetindo a mensagem:

 url:
 => visit: 0.655499 seconds at C:/Perl64/site/lib/HTML/Robot/Scrapper/Benchmark/
Default.pm line 48.
 => busca_ano: 0.04158 seconds at C:/Perl64/site/lib/HTML/Robot/Scrapper/Benchma
rk/Default.pm line 48.
 => Total: : 0.698678 seconds at C:/Perl64/site/lib/HTML/Robot/Scrapper/Benchmar
k/Default.pm line 48.
--[ 1582 ]----------------------------------------------------------------------------------------------------------------

E o arquivo fipe.json não é atualizado. Pode verificar? Obrigado

André da Silva Medeiros

**Comment by hernan604** [comment]
esta certinho, tente debugar os objetos e verifique que eles estao sendo populados corretamente.
